spring:
  application:
    name: parser

  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      location: D:/multipart-temp
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 9090

app:
  storage:
    upload-dir: uploads
